### ISSUE TITLE
Python implementation request

### ISSUE THREAD

**Issue by impredicative** [HongtengXu/Hawkes-Process-Toolkit#1]
This is a cool project, but the availability of Matlab is very constrained. Is it possible to provide a Python 3.7 implementation? I know this is a lot to ask, but then a lot more people can actually use it. Thanks.

**Comment by majkee15** [comment]
have you tried tick? https://github.com/X-DataInitiative/tick/tree/master/lib

**Comment by Jbollenbacher** [comment]
I have found that the tick implementation of some of these inference methods are incorrect.  In particular the [Learning Granger Causality method](https://arxiv.org/abs/1602.04511) is not properly implemented in tick (see relevant issues [here](https://github.com/X-DataInitiative/tick/issues/476)).

The community still requires a proper python implementation of this very useful method.
